language: python
python:
    - "3.7"

os: linux

addons:
    apt:
      update: true
    homebrew:
      update: true

before_install:
    - ./scripts/install_mpi.sh openmpi
    - pip install torch

install:
    pip install .

script:
    - make test
