language: python
python:
    - "3.7"

os: linux

addons:
    apt:
      update: true
    homebrew:
      update: true

before_install:
    - ./scripts/install_mpi.sh mpich
    - pip install torch tensorflow

install:
    - pip install .

script:
    - mv bluefog _bluefog  # Force to use installed package instead of local one
    - make test

# Build and deploy the doc through the sphinx.
before_deploy:
    - pip install sphinx sphinx_rtd_theme
    - cd docs && make html
    - touch _build/html/.nojekyll

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: docs/_build/html/
    on:
        branch: master
